### ISSUE TITLE
seems autolink not work

### ISSUE THREAD

**Issue by z5980000** [arniu/react-native-ionicons#11]
the latest version 4.6.1 can not be detected by autolink with RN 0.61.2
![image](https://user-images.githubusercontent.com/18286633/66971515-1f3f2900-f0c4-11e9-82bb-34ec1fa42467.png)

**Comment by arniu** [comment]
We've not provided a podspec. I'll fix it soon.

**Comment by arniu** [comment]
Fixed, see #12
