### ISSUE TITLE
Icon Name Mismatches

### ISSUE THREAD

**Issue by objectiveSee** [arniu/react-native-ionicons#20]
Hey! I am finding it hard to pick Ionicons for my RN app because the names used in this module don't match the names used in https://ionicons.com/. For example, there's an icon called `ios-stats` which doesn't exists in https://ionicons.com/. It seems like there's some name modifying (adding `ios` prefix) going on. Can someone clarify how they browse icons so you can find the right name? When do we need to prepend `ios` to a name? Thanks!

I get this warning all the time when using the icon names from Ionicon website. It's hard to scan this yellow list and pick the "real" names from it.

<img width="495" alt="Screen Shot 2020-05-26 at 12 04 35 PM" src="https://user-images.githubusercontent.com/1684106/82940069-24613200-9f49-11ea-97e4-a8a825b675d2.png">

**Comment by arniu** [comment]
Use v4 please~

**Comment by objectiveSee** [comment]
Okay I got it. thanks!
