### ISSUE TITLE
Icon is not showing, instead chinese?

### ISSUE THREAD

**Issue by usama-asfar** [arniu/react-native-ionicons#22]
I have installed `react-native-ionicons` on my react-native project 
```json
 "react": "16.13.1",
 "react-native": "0.63.2",
"react-native-ionicons": "^4.6.5",
```

the code 
```js
import Icon from 'react-native-ionicons';

export default function () {
  return (
    <View>
      <Icon ios="ios-add" android="md-add" />
    </View>
  );
}
```

the screenshot
![Screenshot_20200825-234516_adex 1](https://user-images.githubusercontent.com/42825498/91211940-2ba50100-e72d-11ea-80ce-58f86f6b1432.jpg)

**Comment by someAndroidDeveloper** [comment]
Same with me. I used it with bottom tab navigator, also tried to remove and add it again with yarn and reinstalled both node modules and the application itself.
nothing changed.

**Comment by usama-asfar** [comment]
issue solved by linking the library 

```
npx react-native link react-native-ionicons
```
