### ISSUE TITLE
Deprecated warning

### ISSUE THREAD

**Issue by arpansahoo** [arniu/react-native-ionicons#8]
I'm getting this message from Metro:

warn The following packages use deprecated "rnpm" config that will stop working from next release:
  - react-native-ionicons: https://github.com/fanqfanh/react-native-ionicons#readme
Please notify their maintainers about it. You can find more details at https://react-native-community/cli/docs/configuration.md#migration-guide.

**Comment by arniu** [comment]
Fixed. Thanks very much😊
